apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-quay-test-full
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-quay-test-full 
  name: py-quay-test-full
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-quay-test-full 
